3. Разметка страницы формы
htmlacademy-adaptive/1408611-cat-energy-22 pull request #3
Opened 2021-04-15 22:43 UTC by ayqod

2021-04-16 07:45 UTC, Shramkoweb requested changes

2021-04-16 07:45 UTC, Shramkoweb commented on package.json
> +  "dependencies": {}
Верни как было и `package-lock.json` тоже

2021-04-16 07:45 UTC, Shramkoweb commented on source/form.html
> +      <a class="page-header__logo">
А вот теперь мы уже на форме, и логотип ведет назад на главную. Будь внимателен

2021-04-16 07:45 UTC, Shramkoweb commented on source/form.html
> +            <a class="nav-list__link" href="#!">Главная</a>
Аналогично - ссылка на главную)

2021-04-16 07:45 UTC, Shramkoweb commented on source/form.html
> +            <a class="nav-list__link" href="form.html">Подбор программы</a>
Мы уже на форме - отсюда убрать ссылку)

2021-04-16 07:45 UTC, Shramkoweb commented on source/form.html
> +                <label class="form__label" for="cat-name">ИМЯ:*</label>
Бизнесс область нашего приложения на данный момент коты - поэтому в каждом поле добавлять префикс cat-name, cat-weight как по мне лишнее. Мы и так знаем, что это кот. Я бы убрал

2021-04-16 07:45 UTC, Shramkoweb commented on source/form.html
> +                <label class="form__label" for="cat-name">ИМЯ:*</label>
FYI

2021-04-17 20:10 UTC, ayqod commented on package.json
> +  "dependencies": {}
✅

2021-04-17 20:11 UTC, ayqod commented on source/form.html
> +      <a class="page-header__logo">
✅

2021-04-17 20:12 UTC, ayqod commented on source/form.html
> +            <a class="nav-list__link" href="#!">Главная</a>
✅

2021-04-17 20:13 UTC, ayqod commented on source/form.html
> +            <a class="nav-list__link" href="form.html">Подбор программы</a>
Очень извиняться:)

2021-04-17 20:16 UTC, ayqod commented on source/form.html
> +                <label class="form__label" for="cat-name">ИМЯ:*</label>
✅

2021-04-17 21:26 UTC, ayqod commented on source/form.html
> +                <label class="form__label" for="keeper-email">e-mail:*</label>
Так это не имя кота, а слово:) но если ты в том плане, чтобы сократить название -- согласен:)

2021-04-17 21:27 UTC, ayqod commented on source/form.html
> +                <label class="form__label" for="keeper-phone">Телефон:*</label>
✅

2021-04-18 08:05 UTC, Shramkoweb approved these changes
LGTM 👍

2021-04-18 08:06 UTC, merged